schema = "https://raw.githubusercontent.com/Outer-Wilds-New-Horizons/new-horizons/refs/heads/main/NewHorizons/Schemas/text_schema.xsd"
file_type = "NomaiObject"

[[text_block]]
id = 1
text = "HYACINTH: Alright, the beacon is in place, now to activate it!"

[[text_block]]
id = 2
parent = 1
text = "HYACINTH: Actually... should I..?"

[[text_block]]
id = 3
parent = 2
text = "HYACINTH: Wait... what is that blocking the sun?"

[[text_block]]
id = 4
parent = 3
text = "[Inactive for 30 seconds, ending recording.]"
