[package]
name = "nh-toml-to-xml"
version = "1.0.1"
edition = "2021"

[dependencies]
quick-xml = "0.36.2"

[dependencies.toml]
version = "0.8.19"
features = ["parse"]

[dependencies.serde]
version = "1.0.210"
features = ["derive"]

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
