file_type = "DialogueTree"
name_field = "Softlock"

[[dialogue_node]]
id = "START"
entry_condition = "DEFALT" # Typo you may make
[[dialogue_node.dialogue]]
page = ["Unreachable, since you're stuck before this"]
